x-global-envs:
  &global-envs
    PROBLEM_TYPE: regression
    MODEL: house-pricing-tree-regressor
    LABEL: SalePrice
    RANDOM_STATE: 0
    TEST_SIZE: 0.3
    HOST: "0.0.0.0"
    PORT: 80

services:
    ml-server-a:
        container_name: ml-server-a
        build:
            context: .
            dockerfile: "Dockerfile.server"
        environment:
            <<: *global-envs
            DATA_DIR: data/house_pricing/A
        networks:
            app_network:
                ipv4_address: 192.168.100.10
        ports:
            - "80:80"
        stdin_open: true 
        tty: true

    ml-server-b:
        container_name: ml-server-b
        build:
            context: .
            dockerfile: "Dockerfile.server"
        environment:
            <<: *global-envs
            DATA_DIR: data/house_pricing/B
        networks:
            app_network:
                ipv4_address: 192.168.100.11
        ports:
            - "81:80"
        stdin_open: true 
        tty: true

    ml-server-c:
        container_name: ml-server-c
        build:
            context: .
            dockerfile: "Dockerfile.server"
        environment:
            <<: *global-envs
            DATA_DIR: data/house_pricing/C
        networks:
            app_network:
                ipv4_address: 192.168.100.12
        ports:
            - "82:80"
        stdin_open: true 
        tty: true

    proxy:
        container_name: proxy
        build:
            context: .
            dockerfile: "Dockerfile.proxy"
        networks:
            app_network:
                ipv4_address: 192.168.100.13
        ports:
            - "83:80"
        stdin_open: true 
        tty: true

networks:
    app_network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.100.0/24