x-global-envs:
  &global-envs
    ML_SERVERS_NUMBER: 4
    PROBLEM_TYPE: regression
    MODEL: house-pricing-tree-regressor
    LABEL: SalePrice
    #MODEL: metro-tree-regressor
    #LABEL: Oil_temperature
    RANDOM_STATE: 0
    TEST_SIZE: 0.3

services:
    ml-server-1:
        container_name: ml-server-1
        build:
            context: .
            dockerfile: "Dockerfile.server"
        environment:
            <<: *global-envs
            #DATA_DIR: data/metro_reduced/A
            DATA_DIR: data/house_pricing/A
        networks:
            app_network:
                ipv4_address: 192.168.100.10
        ports:
            - "80:80"
        stdin_open: true
        tty: true

    ml-server-2:
        container_name: ml-server-2
        build:
            context: .
            dockerfile: "Dockerfile.server"
        environment:
            <<: *global-envs
            #DATA_DIR: data/metro_reduced/B
            DATA_DIR: data/house_pricing/B
        networks:
            app_network:
                ipv4_address: 192.168.100.11
        ports:
            - "81:80"
        stdin_open: true
        tty: true

    ml-server-3:
        container_name: ml-server-3
        build:
            context: .
            dockerfile: "Dockerfile.server"
        environment:
            <<: *global-envs
            #DATA_DIR: data/metro_reduced/C
            DATA_DIR: data/house_pricing/C
        networks:
            app_network:
                ipv4_address: 192.168.100.12
        ports:
            - "82:80"
        stdin_open: true
        tty: true

    ml-server-4:
        container_name: ml-server-4
        build:
            context: .
            dockerfile: "Dockerfile.server"
        environment:
            <<: *global-envs
            #DATA_DIR: data/metro_reduced/D
            DATA_DIR: data/house_pricing/D
        networks:
            app_network:
                ipv4_address: 192.168.100.13
        ports:
            - "83:80"
        stdin_open: true
        tty: true

    proxy:
        container_name: proxy
        build:
            context: .
            dockerfile: "Dockerfile.proxy"
        environment:
            <<: *global-envs
        networks:
            app_network:
                ipv4_address: 192.168.100.20
        ports:
            - "90:80"
        stdin_open: true
        tty: true

networks:
    app_network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.100.0/24
