services:

    shared_resource:
        container_name: prototipo_ML
        build:
            context: .
            dockerfile: "Dockerfile"
        networks:
            app_network:
                ipv4_address: 192.168.100.10
        stdin_open: true 
        tty: true        


networks:

    app_network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.100.0/24